spring.application.name=cdn_project
spring.datasource.username=efeaksu
spring.datasource.url=jdbc:postgresql://localhost:5432/movie
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
omdb.api.key=226a063e

server.port=8080